### ISSUE TITLE
updated value twice

### ISSUE THREAD

**Issue by cjprinse** [blobule/habpanel-thermoknob-widget#1]
Item is updated twice.

When I change the setpoint, then the connected Item is updated twice.
My nefit thermostat is connected via an mqtt bridge/broker to a openhab item

I receive the setSetpointCommand twice.
This is a problem, because for some reason the nefit-easy-commands library cannot handle closely called requests well. I think this has something to do with queuing and promises.

When I use a habpanel button to set the setpoint, I only receive the update, once (which is excepted)

That is why I think the issue is in the thermoknob-widget.

**Comment by blobule** [comment]
It is very possible that the widget is sending a command twice.
Is it when you click directly on a position or after you drag the widget to a new position? (click and drag are not handled exactly the same).
I can fix this quite easily I think... just confirm if it happens for click, drag, or both...

**Comment by cjprinse** [comment]
I've just verified. It occurs both, when clicking and when dragging.

Thank you for willing to fix this :)

**Comment by blobule** [comment]
d3 was tracking 'dragend' and 'click' at the same time, resulting in two commands sent.
Issue solved!
