### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by tomitrescak** [blobule/habpanel-thermoknob-widget#3]
This looks awesome, but for some reason it does not allow me to install it as it is stuck on go to repository screen

**Comment by blobule** [comment]
Hi,
I updated the github link in the original openhab community post.
Please try again and tell me if you can use "go to repository" and then "install widget".
Remember that you will have to install manually a directory, as you will see in the install instructions.

I hope this fixes it. Keep me posted!
